//! GPU-only corner stencils for actual fractional lake probes. Optional scratch;
//! unsupported graphs/coordinates/limits retain ordinary composed GPU sampling.
use super::{RegistryProgram, composition::CachedDensity, interpolation::CachePlan};
use crate::GpuRequest;
use std::borrow::Cow;
use std::fmt::Write;

pub(crate) const FLAG: u32 = 1 << 25;
pub(crate) const SOURCE_KEY: &str = "// sparse registered lake interpolation stencils";
const SOURCE_END: &str = "// end sparse registered lake interpolation stencils";

/// The lake helpers use the world binding layout and world-only probe functions.
/// A profile's cave modules share its graph source, but cannot include these helpers.
pub(crate) fn without_source(source: &str) -> Cow<'_, str> {
    match (source.find(SOURCE_KEY), source.find(SOURCE_END)) {
        (Some(start), Some(end)) => Cow::Owned(format!(
            "{}{}",
            &source[..start],
            &source[end + SOURCE_END.len()..]
        )),
        _ => Cow::Borrowed(source),
    }
}

#[derive(Clone)]
pub(crate) struct Plan {
    fields: Vec<(usize, [u32; 2], u32)>,
    terrain_cell: [u32; 2],
}
impl Plan {
    pub fn new(program: &RegistryProgram) -> Option<Self> {
        if !program.terrain_cell.into_iter().all(u32::is_power_of_two) {
            return None;
        }
        let primary = CachedDensity::new(program)?;
        let pure = CachePlan::new(program);
        let fields = primary
            .fields()
            .iter()
            .map(|&(field, cell)| {
                let columns = program.terrain_cell[0].div_ceil(cell[0]) + 3;
                (field, cell, columns)
            })
            .collect::<Vec<_>>();
        if fields.iter().any(|&(field, cell, columns)| {
            !pure.retains(field) || columns > 64 || cell.into_iter().any(|v| v > 8_388_608)
        }) {
            return None;
        }
        Some(Self {
            fields,
            terrain_cell: program.terrain_cell,
        })
    }
    pub fn field_count(&self) -> u32 {
        self.fields.len() as u32
    }
    fn rows(cell_y: u32, r: &GpuRequest) -> u64 {
        let step = i64::from(r.density_step_y);
        let bottom = i64::from(r.min_y).div_euclid(step) * step;
        let top = bottom + (i64::from(r.max_y) - bottom + step - 1) / step * step;
        let sy = i64::from(cell_y);
        (-(-top).div_euclid(sy) - bottom.div_euclid(sy) + 1) as u64
    }
    pub fn words(&self, r: &GpuRequest) -> u64 {
        self.fields
            .iter()
            .map(|&(_, cell, columns)| u64::from(columns).pow(2) * Self::rows(cell[1], r))
            .sum()
    }
    pub fn max_samples(&self, r: &GpuRequest) -> u64 {
        self.fields
            .iter()
            .map(|&(_, cell, columns)| u64::from(columns).pow(2) * Self::rows(cell[1], r))
            .max()
            .unwrap_or(0)
    }
    /// Reads remain exact within this binary-grid domain. This only selects an
    /// accelerator; an ineligible request is generated by the original sampler.
    pub fn request_supported(&self, r: &GpuRequest) -> bool {
        let width = i64::from(r.tile_side.max(1)) * 16;
        let margin = 512i64;
        let limit = 8_388_608i64;
        let step = i64::from(r.density_step_y);
        if step == 0 || step > limit {
            return false;
        }
        let bottom = i64::from(r.min_y).div_euclid(step) * step;
        let top = bottom + (i64::from(r.max_y) - bottom + step - 1) / step * step;
        r.density_side > 0
            && [r.density_step_xz, r.density_step_y] == self.terrain_cell
            && r.density_step_xz.is_power_of_two()
            && r.density_step_y.is_power_of_two()
            && r.density_step_xz <= limit as u32
            && bottom >= -limit
            && top <= limit
            && [i64::from(r.origin_x), i64::from(r.origin_z)]
                .into_iter()
                .all(|lo| lo - margin >= -limit && lo + width + margin <= limit)
            && self.fields.iter().all(|&(_, cell, _)| {
                let sy = i64::from(cell[1]);
                i64::from(r.min_y) - sy >= -limit && i64::from(r.max_y) + sy <= limit
            })
    }
    pub fn source(&self, horizontal: u32) -> String {
        let mut code = format!(
            "\n{SOURCE_KEY}\nvar<private> lake_sparse_probe:u32=0xffffffffu;\nstruct LakeSparseLayout{{origin:vec3<i32>,size:vec3<u32>}}\nfn lake_sparse_offset(r:Request)->u32{{return column_offset(r)+r.density_side*r.density_side*{horizontal}u;}}\n"
        );
        let mut prefixes = Vec::new();
        for &(field, cell, columns) in &self.fields {
            let [sx, sy] = cell;
            writeln!(code,"fn lake_sparse_rows_{field}(r:Request)->u32{{let bottom=density_floor_div(density_origin(r).y,{sy});let top=density_origin(r).y+i32((density_layers(r)-1u)*r.density_step_y);return u32(-density_floor_div(-top,{sy})-bottom+1);}}\nfn lake_sparse_words_{field}(r:Request)->u32{{return {columns}u*{columns}u*lake_sparse_rows_{field}(r);}}").unwrap();
            writeln!(code,"fn lake_sparse_layout_{field}(probe:u32,r:Request)->LakeSparseLayout{{
let p=lake_probe_point(probe,r);let step=f32(r.density_step_xz);let o=vec2<f32>(density_origin(r).xz);
let lo=o+floor((p-o)/step)*step;let hi=lo+vec2<f32>(step);
let lower=floor(min(lo,p)/{sx}.0)*{sx}.0;let upper=ceil(max(hi,p)/{sx}.0)*{sx}.0;
let bottom=density_floor_div(density_origin(r).y,{sy})*{sy};
return LakeSparseLayout(vec3<i32>(i32(lower.x),bottom,i32(lower.y)),vec3<u32>(u32((upper.x-lower.x)/{sx}.0)+1u,lake_sparse_rows_{field}(r),u32((upper.y-lower.y)/{sx}.0)+1u));
}}").unwrap();
            let prefix = if prefixes.is_empty() {
                "0u".to_owned()
            } else {
                prefixes.join("+")
            };
            writeln!(
                code,
                "fn lake_sparse_prefix_{field}(r:Request)->u32{{return {prefix};}}"
            )
            .unwrap();
            prefixes.push(format!("lake_sparse_words_{field}(r)"));
        }
        writeln!(
            code,
            "fn lake_sparse_stride(r:Request)->u32{{return {};}}",
            prefixes.join("+")
        )
        .unwrap();
        let maximum = prefixes
            .iter()
            .skip(1)
            .fold(prefixes[0].clone(), |a, b| format!("max({a},{b})"));
        writeln!(
            code,
            "fn lake_sparse_max(r:Request)->u32{{return {maximum};}}"
        )
        .unwrap();
        code.push_str("fn lake_sparse_corner(field:u32,point:vec3<f32>,r:Request)->vec2<f32>{\nif lake_sparse_probe==0xffffffffu || (r.padding&33554432u)==0u{return vec2<f32>(0.0);}\nswitch field{\n");
        for &(field, [sx, sy], columns) in &self.fields {
            writeln!(code,"case {field}u:{{let shape=lake_sparse_layout_{field}(lake_sparse_probe,r);let step=vec3<i32>({sx},{sy},{sx});let local=(point-vec3<f32>(shape.origin))/vec3<f32>(step);let cell=vec3<i32>(local);if any(local!=vec3<f32>(cell)) || any(cell<vec3<i32>(0)) || any(cell>=vec3<i32>(shape.size)) || any(point!=vec3<f32>(shape.origin+cell*step)){{return vec2<f32>(0.0);}}let offset=lake_sparse_offset(r)+lake_sparse_probe*lake_sparse_stride(r)+lake_sparse_prefix_{field}(r);let at=(u32(cell.y)*{columns}u+u32(cell.z))*{columns}u+u32(cell.x);return vec2<f32>(surface_nodes[offset+at],1.0);}}").unwrap();
        }
        code.push_str("default:{return vec2<f32>(0.0);}}}\n@compute @workgroup_size(64) fn lake_sparse_fields(@builtin(global_invocation_id) id:vec3<u32>){\nlet r=requests[id.z];if (r.padding&33554432u)==0u{return;}let maximum=lake_sparse_max(r);let probe=id.x/maximum;let sample=id.x%maximum;if probe>=lake_side(r)*lake_side(r)*5u || surface_nodes[lake_offset(r)+(probe/5u)*4u+3u]<0.5{return;}\nswitch id.y{\n");
        for (slot, &(field, [sx, sy], columns)) in self.fields.iter().enumerate() {
            writeln!(code,"case {slot}u:{{let shape=lake_sparse_layout_{field}(probe,r);let cell=vec3<u32>(sample%{columns}u,sample/({columns}u*{columns}u),sample/{columns}u%{columns}u);if any(cell>=shape.size){{return;}}let point=vec3<f32>(shape.origin+vec3<i32>(cell)*vec3<i32>({sx},{sy},{sx}));let cached=interpolation_cached_corner({field}u,point,r);if cached.y!=0.0{{return;}}let at=lake_sparse_offset(r)+probe*lake_sparse_stride(r)+lake_sparse_prefix_{field}(r)+sample;surface_nodes[at]=run_interpolation_input({field}u,point,r);}}").unwrap();
        }
        writeln!(code, "default:{{}}}}}}\n{SOURCE_END}").unwrap();
        code
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    fn registry_fixture() -> RegistryProgram {
        serde_json::from_value(serde_json::json!({
            "programs":[
                {"nodes":[{"op":0,"a":0,"b":0,"c":0,"p":[0,0,0,0]}],"roots":[0]},
                {"nodes":[
                    {"op":29,"a":0,"b":0,"c":0,"p":[0,0,0,0]},
                    {"op":29,"a":1,"b":0,"c":0,"p":[0,0,0,0]},
                    {"op":29,"a":2,"b":0,"c":0,"p":[0,0,0,0]},
                    {"op":28,"a":0,"b":1,"c":2,"p":[0,0,0,0]}],"roots":[3]}],
            "noises":[],"points":[],"surface":[-64,8,0],"terrain_cell":[4,8],
            "interpolations":[{"cell":[2,4],"input":{"nodes":[{"op":0,"a":0,"b":0,"c":0,"p":[1,0,0,0]}],"roots":[0]}}]
        })).unwrap()
    }
    fn request() -> GpuRequest {
        GpuRequest {
            origin_x: -33,
            origin_z: -129,
            min_y: -67,
            max_y: 319,
            seed_low: 123456789,
            seed_high: 0,
            base_height: 64.0,
            amplitude: 48.0,
            frequency: 0.008,
            profile: 1,
            tile_side: 0,
            padding: 0,
            density_offset: 0,
            density_side: 9,
            density_step_xz: 4,
            density_step_y: 8,
        }
    }
    #[test]
    fn sparse_plan_uses_rounded_global_rows_and_rejects_uncovered_contexts() {
        let mut registry = registry_fixture();
        let plan = Plan::new(&registry).unwrap();
        let mut r = request();
        // Density nodes cover -72..320; the finer field has 99 distinct Y rows.
        assert_eq!(plan.words(&r), 25 * 99);
        assert_eq!(plan.max_samples(&r), 25 * 99);
        assert!(plan.request_supported(&r));
        r.min_y = -69;
        r.max_y = -1;
        assert_eq!(plan.words(&r), 25 * 19);
        r.origin_x = 8_388_607;
        assert!(!plan.request_supported(&r));
        r = request();
        r.density_step_xz = 8;
        assert!(!plan.request_supported(&r));
        registry.programs[1].nodes[3].b = 0;
        assert!(Plan::new(&registry).is_none());
        registry = registry_fixture();
        registry.interpolations[0].input.nodes[0].op = 42;
        assert!(Plan::new(&registry).is_none());
        registry = registry_fixture();
        registry.interpolations[0].cell = [3, 5];
        assert!(Plan::new(&registry).is_none());
    }
    #[test]
    fn world_helpers_do_not_leak_into_cave_modules() {
        let source = Plan::new(&registry_fixture()).unwrap().source(3);
        let combined = format!("before\n{source}\nafter");
        let cave = without_source(&combined);
        assert!(cave.starts_with("before"));
        assert!(cave.ends_with("after"));
        assert!(!cave.contains("lake_sparse"));
        assert_eq!(without_source("ordinary source"), "ordinary source");
    }
}

pub(crate) fn cached_source(program: &str) -> String {
    let mut result = program.replace(
        "fn density_composed(r:Request)->bool {return (r.padding&(1u<<26u))!=0u;}",
        "fn density_composed(r:Request)->bool {return true;}",
    );
    for field in 0..program.matches("fn interpolation_field_").count() {
        let original = super::interpolation::specialized(field);
        // Keep the original global corner/mix arithmetic and checked atlas lookup.
        // Sparse probe coverage provides every missing primary-field corner, so
        // the raw input graph is unreachable in this entrypoint.
        let cached = original.replace(
            &format!("interpolation_graph_{field}(point,request,context,program)[0]"),
            "0.0",
        );
        result = result.replace(&original, &cached);
    }
    // Bounds outside the main rectangular atlas keep their original evaluation;
    // their field vertices now come from the sparse probe stencil.
    result = result.replace(
        "if cached.y==0.0 {value=run_interpolation_input(field,point,r);}",
        "if cached.y==0.0 {return bounds_unknown();}",
    );
    result = result.replace(
        "fn interpolation_cached_corner(",
        "fn interpolation_tile_corner(",
    );
    result.push_str("\nfn interpolation_cached_corner(field:u32,point:vec3<f32>,r:Request)->vec2<f32>{let cached=interpolation_tile_corner(field,point,r);if cached.y!=0.0{return cached;}return lake_sparse_corner(field,point,r);}\n");
    result
}
